keys_config_path: 'keys_config.yaml'

error_saving_path: "extracting_errors"

api_data_saving_path:
  imdb: 'raw_imdb_data'
  wiki: 'raw_wiki_data'

vectors_cache_path: 'vectors_cache'

similar_list_saving_path: 'similar_list_data'

doc2vec_model_path: 'enwiki_dbow/doc2vec.bin'

title_to_id_json_name: 'title_to_id.json'